POSTGRES_USER: username
POSTGRES_PASSWORD: password


spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-consumes-media-type: application/json
application:
  title: Project Management System
  security:
    jwt:
      secret-key: 404E635266556A586E32723538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

server:
  servlet:
    context-path: /api/v1/

razorpay:
  api:
    key: rZp_test_5NYr5tfatfgf6
    secret: gYgyajduathajdyghU

