spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kayangejr3@gmail.com
    password: app-password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000